[build]
target = ".cargo/i686.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.i686]
rustflags = [
    "-C",
    "no-redzone=yes",          # -mno-red-zone
    "-C",
    "code-model=kernel",       # wow chat
    "-C",
    "relocation-model=static", # static linking
    "-C",
    "link-arg=-nostdlib",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-nodefaultlibs",
    "-C",
    "link-arg=-static",
    "-C",
    "target-cpu=i686",
    "-C",
    "link-arg=-m32",
    "-C",
    "debuginfo=2",     # full debug info
    "-C",
    "force-frame-pointers=yes",    # -fomit-frame-pointer
]
