[package]
name = "bindsync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
bindgen = "0.71.1"
lazy_static = "1.5.0"
md5 = "0.7.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
walkdir = "2.5.0"
